// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// E_step_testC
List E_step_testC(arma::mat dataXY, int p, int q, int r, int rx, int ry, int N, arma::mat SigmaZ, arma::mat GammaEF, arma::mat invZtilde, arma::mat Gamma, arma::mat GGef, arma::mat EZc, arma::mat Szz, arma::mat W, arma::mat C, arma::mat Wo, arma::mat Co, arma::mat SigT, arma::mat SigH, double sig2E, double sig2F);
RcppExport SEXP _PO2PLS_E_step_testC(SEXP dataXYSEXP, SEXP pSEXP, SEXP qSEXP, SEXP rSEXP, SEXP rxSEXP, SEXP rySEXP, SEXP NSEXP, SEXP SigmaZSEXP, SEXP GammaEFSEXP, SEXP invZtildeSEXP, SEXP GammaSEXP, SEXP GGefSEXP, SEXP EZcSEXP, SEXP SzzSEXP, SEXP WSEXP, SEXP CSEXP, SEXP WoSEXP, SEXP CoSEXP, SEXP SigTSEXP, SEXP SigHSEXP, SEXP sig2ESEXP, SEXP sig2FSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type dataXY(dataXYSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    Rcpp::traits::input_parameter< int >::type rx(rxSEXP);
    Rcpp::traits::input_parameter< int >::type ry(rySEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type SigmaZ(SigmaZSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type GammaEF(GammaEFSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type invZtilde(invZtildeSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Gamma(GammaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type GGef(GGefSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type EZc(EZcSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Szz(SzzSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type C(CSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Wo(WoSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Co(CoSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type SigT(SigTSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type SigH(SigHSEXP);
    Rcpp::traits::input_parameter< double >::type sig2E(sig2ESEXP);
    Rcpp::traits::input_parameter< double >::type sig2F(sig2FSEXP);
    rcpp_result_gen = Rcpp::wrap(E_step_testC(dataXY, p, q, r, rx, ry, N, SigmaZ, GammaEF, invZtilde, Gamma, GGef, EZc, Szz, W, C, Wo, Co, SigT, SigH, sig2E, sig2F));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_PO2PLS_E_step_testC", (DL_FUNC) &_PO2PLS_E_step_testC, 22},
    {NULL, NULL, 0}
};

RcppExport void R_init_PO2PLS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
