# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

E_step_testC <- function(dataXY, p, q, r, rx, ry, N, SigmaZ, GammaEF, invZtilde, Gamma, GGef, EZc, Szz, W, C, Wo, Co, SigT, SigH, sig2E, sig2F) {
    .Call(`_PO2PLS_E_step_testC`, dataXY, p, q, r, rx, ry, N, SigmaZ, GammaEF, invZtilde, Gamma, GGef, EZc, Szz, W, C, Wo, Co, SigT, SigH, sig2E, sig2F)
}

